id: P008213
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-17 13:08:22.718624
source_metadata:
  id: bdr:W1KG22691
  title: དཔལ་རྒྱལ་དབང་ཀརྨ་པ་སྐུ་ཕྲེང་བཅུ་དྲུག་པ་ཚུན་རིམ་པར་བྱོན་པའི་རྣམ་ཐར་ཕྱོགས་བསྒྲིགས།
  author: ''
  volumes:
    9fa3d1097a7f466ebab9de107923db26:
      image_group_id: I1KG22913
      title: ''
      volume_number: 1
      total_pages: 478
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
