id: IEDE4CBB7
legacy_id: P008213
ocr_import_info:
  bdrc_scan_id: W1KG22691
  source: bdrc
  ocr_info:
    timestamp: '2020-03-28T20:34:57'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-27T07:14:14.777831+00:00'
last_modified: 2022-08-27 15:15:00.429426
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG22691
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG22691
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དཔལ་རྒྱལ་དབང་ཀརྨ་པ་སྐུ་ཕྲེང་བཅུ་དྲུག་པ་ཚུན་རིམ་པར་བྱོན་པའི་རྣམ་ཐར་ཕྱོགས་བསྒྲིགས།
  author: མཁན་ཆེན་ཁྲ་འགུ་རིན་པོ་ཆེ།
statistics:
  ocr_word_mean_confidence_index: 0.8442200228751716
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I1KG22913:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG22913
      total_pages: 478
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG22913.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.8442200228751716
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
